stages:
  prepare:
    cmd: python src/data/split_scale_data.py
    deps:
    - data/raw_data/
    - src/data/split_scale_data.py
    outs:
    - data/processed_data/
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed_data
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.joblib
  evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data
    - models/trained_model.joblib
    - src/models/evaluate_model.py
    outs:
    - data/predictions/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
